# Seed Speech TTS 2.0 voices, generated from the official voice list
# https://docs.byteplus.com/en/docs/byteplusvoice/tts-voice-list (last updated 2026-09-10).
# Speaker IDs are saved in workflows: add new voices, never rename existing ones.
# Seed Audio 1.0 also accepts these IDs as speaker references.

# (speaker ID, name, language, gender, scenario)
TTS_2_VOICES = [
    ('en_female_stokie_uranus_bigtts', 'Stokie', 'American English', 'Female', 'General'),
    ('en_female_dacey_uranus_bigtts', 'Dacey', 'American English', 'Female', 'General'),
    ('en_male_tim_uranus_bigtts', 'Tim', 'American English', 'Male', 'General'),
    ('en_female_nadia_uranus_bigtts', 'Blair', 'American English', 'Female', 'General'),
    ('en_male_kevin_uranus_bigtts', 'Kevin', 'American English', 'Male', 'Education'),
    ('en_male_jamie_uranus_bigtts', 'Jamie', 'American English', 'Male', 'General'),
    ('en_female_hayley_uranus_bigtts', 'Hayley', 'American English', 'Female', 'Education'),
    ('en_female_skye_uranus_bigtts', 'Skye', 'American English', 'Female', 'General'),
    ('en_male_bruce_uranus_bigtts', 'Adrian', 'American English', 'Male', 'General'),
    ('en_male_alex_uranus_bigtts', 'Alex', 'American English', 'Male', 'General'),
    ('en_male_yangguangjieshuonan_uranus_bigtts', 'Dylan', 'American English', 'Male', 'General'),
    ('en_male_ronald_uranus_bigtts', 'Ronald', 'American English', 'Male', 'AudioBook'),
    ('en_male_diyuwenrounan_uranus_bigtts', 'Julian', 'American English', 'Male', 'AudioBook'),
    ('en_male_knightley_uranus_bigtts', 'Knightley', 'American English', 'Male', 'AudioBook'),
    ('en_male_fernando-martinez_uranus_bigtts', 'Felix', 'American English', 'Male', 'General'),
    ('en_male_michael_uranus_bigtts', 'Hank', 'American English', 'Male', 'General'),
    ('en_male_josh_uranus_bigtts', 'Josh', 'American English', 'Male', 'Dubbing'),
    ('en_male_simba_p1_uranus_bigtts', 'Simba', 'American English', 'Male', 'General'),
    ('en_male_motivational-coach_uranus_bigtts', 'Rory', 'American English', 'Male', 'Entertainment'),
    ('en_male_marcus_uranus_bigtts', 'Marcus', 'American English', 'Male', 'General'),
    ('en_male_michael_kevin_uranus_bigtts', 'Michael_Kevin', 'American English', 'Male', 'General'),
    ('en_male_valentino_uranus_bigtts', 'Valentino', 'American English', 'Male', 'General'),
    ('en_male_josh_coery_uranus_bigtts', 'Josiah', 'American English', 'Male', 'Education'),
    ('en_male_david_uranus_bigtts', 'David', 'American English', 'Male', 'General'),
    ('en_female_allison_uranus_bigtts', 'Allison', 'American English', 'Female', 'Dubbing'),
    ('en_male_godfather_uranus_bigtts', 'Godfather', 'American English', 'Male', 'AudioBook'),
    ('en_male_evil-guy-oxley_uranus_bigtts', 'Harrison', 'American English', 'Male', 'Dubbing'),
    ('en_male_joker_uranus_bigtts', 'Joker', 'American English', 'Male', 'Entertainment'),
    ('en_female_wenrouzhishijieshuonv_uranus_bigtts', 'Megan', 'American English', 'Female', 'CustomerService'),
    ('en_female_lana_del_rey_parky_s_p1_uranus_bigtts', 'Ivy', 'American English', 'Female', 'CustomerService'),
    ('en_female_jane_uranus_bigtts', 'Jane', 'American English', 'Female', 'Dubbing'),
    ('en_female_rachel_p1_uranus_bigtts', 'Rachel', 'American English', 'Female', 'Entertainment'),
    ('en_male_cowboy-bob_uranus_bigtts', 'Bob', 'American English', 'Male', 'General'),
    ('en_female_brittney_pimintel_uranus_bigtts', 'Zoe', 'American English', 'Female', 'AudioBook'),
    ('en_female_female_tutor_ms-jenny_uranus_bigtts', 'Holly', 'American English', 'Female', 'Education'),
    ('en_female_joanne_uranus_bigtts', 'Joanne', 'American English', 'Female', 'General'),
    ('en_male_bill_jones_corey_uranus_bigtts', 'Bill', 'American English', 'Male', 'General'),
    ('en_male_adam-imitation_uranus_bigtts', 'Rowan', 'American English', 'Male', 'General'),
    ('en_male_brad_pitt_p1_uranus_bigtts', 'Brad_Pitt', 'American English', 'Male', 'General'),
    ('en_male_father-christmas_uranus_bigtts', 'Alfred', 'American English', 'Male', 'General'),
    ('en_male_hades_uranus_bigtts', 'Beau', 'American English', 'Male', 'General'),
    ('en_male_alberto_uranus_bigtts', 'Alberto', 'American English', 'Male', 'General'),
    ('en_female_jenny_uranus_bigtts', 'Jenny', 'American English', 'Female', 'General'),
    ('en_male_valentino_corey_uranus_bigtts', 'Clark', 'American English', 'Male', 'Dubbing'),
    ('en_male_russell_uranus_bigtts', 'Russell', 'American English', 'Male', 'General'),
    ('en_male_tom_hiddleston_p1_uranus_bigtts', 'Tom', 'American English', 'Male', 'General'),
    ('en_female_authoritative-informative_uranus_bigtts', 'Margaret', 'American English', 'Female', 'General'),
    ('en_male_jidongchuanjiaoshi_uranus_bigtts', 'Blaze', 'American English', 'Male', 'Entertainment'),
    ('en_female_myra_uranus_bigtts', 'Myra', 'American English', 'Female', 'Education'),
    ('en_male_bill-jones_uranus_bigtts', 'Jones', 'American English', 'Male', 'Entertainment'),
    ('en_female_pleasant-female_uranus_bigtts', 'Elaine', 'American English', 'Female', 'AudioBook'),
    ('en_female_scarlet_p1_uranus_bigtts', 'Scarlet', 'American English', 'Female', 'CustomerService'),
    ('en_female_brittney_uranus_bigtts', 'Brittney', 'American English', 'Female', 'General'),
    ('en_female_lana_del_rey_kelley_d_p1_uranus_bigtts', 'Lynn', 'American English', 'Female', 'RolePlay'),
    ('en_female_mel_uranus_bigtts', 'Mel', 'American English', 'Female', 'Education'),
    ('en_male_chandler_p1_uranus_bigtts', 'Leo', 'American English', 'Male', 'Entertainment'),
    ('en_female_natasha_uranus_bigtts', 'Natasha', 'American English', 'Female', 'General'),
    ('en_male_cowboy_john_b_uranus_bigtts', 'John', 'American English', 'Male', 'Entertainment'),
    ('en_male_deep-voice_uranus_bigtts', 'Orion', 'American English', 'Male', 'Entertainment'),
    ('en_male_jimmy_uranus_bigtts', 'Jimmy', 'American English', 'Male', 'General'),
    ('en_male_excited-male-voice_uranus_bigtts', 'Jasper', 'American English', 'Male', 'Entertainment'),
    ('en_female_xinwenjieshuonv_uranus_bigtts', 'Kayla', 'American English', 'Female', 'RolePlay'),
    ('en_female_authoritative-british_uranus_bigtts', 'Charlotte', 'American English', 'Female', 'Education'),
    ('en_female_myra_cmb_uranus_bigtts', 'Sunny', 'American English', 'Female', 'Education'),
    ('en_female_zendaya_p1_uranus_bigtts', 'Zendaya', 'American English', 'Female', 'Education'),
    ('en_male_michael-mouse_uranus_bigtts', 'Chip', 'American English', 'Male', 'Entertainment'),
    ('en_male_gollum_uranus_bigtts', 'Gollum', 'American English', 'Male', 'RolePlay'),
    ('en_female_sharron_uranus_bigtts', 'Sharron', 'American English', 'Female', 'Entertainment'),
    ('zh_female_vv_uranus_bigtts', 'Vivi', 'Chinese', 'Female', 'General'),
    ('zh_male_m191_uranus_bigtts', 'Kian', 'Chinese', 'Male', 'General'),
    ('zh_male_taocheng_uranus_bigtts', 'Cedric', 'Chinese', 'Male', 'General'),
    ('zh_female_xiaohe_uranus_bigtts', 'Mindy', 'Chinese', 'Female', 'General'),
    ('zh_female_jitangnv_uranus_bigtts', 'Nadia', 'Chinese', 'Female', 'General'),
    ('zh_female_xiaoxue_uranus_bigtts', 'Lyla', 'Chinese', 'Female', 'General'),
    ('zh_male_shaonianzixin_uranus_bigtts', 'Jess', 'Chinese', 'Male', 'General'),
    ('zh_female_cancan_uranus_bigtts', 'Corinne', 'Chinese', 'Female', 'General'),
    ('zh_female_yingyujiaoxue_uranus_bigtts', 'Jean', 'Chinese', 'Female', 'General'),
    ('zh_female_meilinvyou_uranus_bigtts', 'Opal', 'Chinese', 'Female', 'General'),
    ('zh_male_ruyayichen_uranus_bigtts', 'Quentin', 'Chinese', 'Male', 'General'),
    ('zh_female_liuchangnv_uranus_bigtts', 'Pearl', 'Chinese', 'Female', 'General'),
    ('zh_female_linjianvhai_uranus_bigtts', 'Pinky', 'Chinese', 'Female', 'General'),
    ('zh_female_peiqi_uranus_bigtts', 'Holly', 'Chinese', 'Female', 'General'),
    ('zh_male_sophie_uranus_bigtts', 'Sophie', 'Chinese', 'Female', 'General'),
    ('zh_female_tianmeixiaoyuan_uranus_bigtts', 'Esther', 'Chinese', 'Female', 'General'),
    ('zh_female_sajiaoxuemei_uranus_bigtts', 'Sandy', 'Chinese', 'Female', 'General'),
    ('zh_male_sunwukong_uranus_bigtts', 'Monkey King', 'Chinese', 'Male', 'General'),
    ('zh_female_shuangkuaisisi_uranus_bigtts', 'Gigi', 'Chinese', 'Female', 'General'),
    ('zh_female_kefunvsheng_uranus_bigtts', 'Tracy', 'Chinese', 'Female', 'General'),
    ('zh_male_dayi_uranus_bigtts', 'Magnus', 'Chinese', 'Male', 'General'),
    ('zh_female_mizai_uranus_bigtts', 'Mabel', 'Chinese', 'Female', 'General'),
    ('zh_female_yuanqi_uranus_bigtts', 'Daisy', 'Chinese', 'Female', 'General'),
    ('ja_female_minimi_uranus_bigtts', 'Minimi', 'Japanese', 'Female', 'General'),
    ('ja_female_bv024_uranus_bigtts', 'Bonnie', 'Japanese', 'Female', 'General'),
    ('ja_male_bv524_uranus_bigtts', 'Ken', 'Japanese', 'Male', 'General'),
    ('ja_female_bv522_uranus_bigtts', 'Hana', 'Japanese', 'Female', 'General'),
    ('ja_female_bv523_uranus_bigtts', 'Lily', 'Japanese', 'Female', 'Entertainment'),
    ('ja_female_shirou_uranus_bigtts', 'Shirou', 'Japanese', 'Female', 'Dubbing'),
    ('ja_female_bv520_uranus_bigtts', 'Poppy', 'Japanese', 'Female', 'Dubbing'),
    ('ja_female_bv521_uranus_bigtts', 'Aoi', 'Japanese', 'Female', 'Entertainment'),
    ('id_male_han_uranus_bigtts', 'Han', 'Indonesian Bahasa', 'Male', 'General'),
    ('id_female_phulia_uranus_bigtts', 'Phulia', 'Indonesian', 'Female', 'General'),
    ('id_male_bv160_uranus_bigtts', 'Rocco', 'Indonesian', 'Male', 'General'),
    ('id_female_bv164_uranus_bigtts', 'Crew', 'Indonesian', 'Female', 'General'),
    ('id_female_bv161_uranus_bigtts', 'Clara', 'Indonesian', 'Female', 'General'),
    ('id_male_m08_uranus_bigtts', 'Kyle', 'Indonesian', 'Male', 'General'),
    ('id_male_bv164narration_uranus_bigtts', 'Ronan', 'Indonesian', 'Male', 'AudioBook'),
    ('id_female_f20_uranus_bigtts', 'Chloe', 'Indonesian', 'Female', 'Dubbing'),
    ('id_male_bv160dialogue_uranus_bigtts', 'Jude', 'Indonesian', 'Male', 'General'),
    ('id_male_bv164dialogue_uranus_bigtts', 'Elian', 'Indonesian', 'Male', 'Dubbing'),
    ('id_male_bv160narration_uranus_bigtts', 'Hugo', 'Indonesian', 'Male', 'AudioBook'),
    ('id_female_bv161narration_uranus_bigtts', 'Celeste', 'Indonesian', 'Female', 'General'),
    ('id_female_bv161dialogue_uranus_bigtts', 'Sylvia', 'Indonesian', 'Female', 'General'),
    ('th_female_bv568_neutral_uranus_bigtts', 'Mildred', 'Thai', 'Female', 'General'),
    ('th_female_bv568_angry_uranus_bigtts', 'Valeria', 'Thai', 'Female', 'Education'),
    ('th_female_bv568_suprise_uranus_bigtts', 'Phoebe', 'Thai', 'Female', 'AudioBook'),
    ('th_female_bv568_hate_uranus_bigtts', 'Valentina', 'Thai', 'Female', 'General'),
    ('th_female_bv568_happy_uranus_bigtts', 'Zara', 'Thai', 'Female', 'General'),
    ('th_female_bv568_sad_uranus_bigtts', 'Lydia', 'Thai', 'Female', 'Dubbing'),
    ('th_female_bv568_fear_uranus_bigtts', 'Iris', 'Thai', 'Female', 'AudioBook'),
    ('vi_female_partner_uranus_bigtts', 'Partner', 'Vietnamese', 'Female', 'Dubbing'),
    ('vi_female_ruan_uranus_bigtts', 'Ruan', 'Vietnamese', 'Female', 'General'),
    ('vi_female_ling_uranus_bigtts', 'Ling', 'Vietnamese', 'Female', 'General'),
    ('vi_female_linh_uranus_bigtts', 'Linh', 'Vietnamese', 'Female', 'Dubbing'),
    ('vi_female_wu_uranus_bigtts', 'Wu', 'Vietnamese', 'Female', 'General'),
    ('vi_female_hong_uranus_bigtts', 'Hong', 'Vietnamese', 'Female', 'General'),
    ('vi_male_wumg_uranus_bigtts', 'Wumg', 'Vietnamese', 'Male', 'General'),
    ('ko_male_shane_uranus_bigtts', '', 'Korean', 'Male', 'AudioBook'),
    ('ko_female_bv546_uranus_bigtts', 'Momo', 'Korean', 'Female', 'Dubbing'),
    ('ko_male_bv545_uranus_bigtts', 'Jay', 'Korean', 'Male', 'General'),
    ('ko_male_m03_uranus_bigtts', 'Minho', 'Korean', 'Male', 'General'),
    ('ms_male_naim_uranus_bigtts', 'Naim', 'Malay', 'Male', 'General'),
    ('ms_male_ham_uranus_bigtts', 'Ham', 'Malay', 'Male', 'General'),
    ('tl_female_annika_uranus_bigtts', 'Annika', 'Filipino', 'Female', 'General'),
    ('tl_female_hervie_uranus_bigtts', 'Hervie', 'Filipino', 'Female', 'AudioBook'),
    ('tl_male_ed_uranus_bigtts', 'Ed', 'Filipino', 'Male', 'General'),
    ('mx_male_marcelo_uranus_bigtts', 'Marcelo', 'Mexican Spanish', 'Male', 'General'),
    ('mx_male_felipe_uranus_bigtts', 'Felipe', 'Mexican Spanish', 'Male', 'General'),
    ('mx_female_leslie_uranus_bigtts', 'Leslie', 'Mexican Spanish', 'Female', 'General'),
    ('mx_female_bv065_uranus_bigtts', 'Irene', 'Mexican Spanish', 'Female', 'Education'),
    ('mx_male_bv165narrator_uranus_bigtts', 'Marcos', 'Mexican Spanish', 'Male', 'AudioBook'),
    ('mx_male_ht_mx_m012_uranus_bigtts', 'Derek', 'Mexican Spanish', 'Male', 'Education'),
    ('mx_female_bv166dialogue_uranus_bigtts', 'Lucy', 'Mexican Spanish', 'Female', 'General'),
    ('mx_male_bv165dialogue_uranus_bigtts', 'Diego', 'Mexican Spanish', 'Male', 'AudioBook'),
    ('mx_female_bv166narrator_uranus_bigtts', 'Freya', 'Mexican Spanish', 'Female', 'AudioBook'),
    ('mx_female_bv166emotion_uranus_bigtts', 'Rosa', 'Mexican Spanish', 'Female', 'General'),
    ('pt_female_mari_uranus_bigtts', 'Mari', 'Brazilian Portuguese', 'Female', 'Education'),
    ('pt_male_martins_uranus_bigtts', 'Martins', 'Brazilian Portuguese', 'Male', 'General'),
    ('pt_male_rael_uranus_bigtts', 'Rael', 'Brazilian Portuguese', 'Male', 'Education'),
    ('pt_female_bv530_uranus_bigtts', 'Sofia', 'Brazilian Portuguese', 'Female', 'General'),
    ('pt_male_bv531_uranus_bigtts', 'Arthur', 'Brazilian Portuguese', 'Male', 'General'),
    ('pt_male_bv172narrator_uranus_bigtts', 'Miles', 'Brazilian Portuguese', 'Male', 'AudioBook'),
    ('pt_female_bv173narrator_uranus_bigtts', 'Emma', 'Brazilian Portuguese', 'Female', 'Dubbing'),
    ('pt_male_bv172dialogue_uranus_bigtts', 'Walter', 'Brazilian Portuguese', 'Male', 'Dubbing'),
    ('pt_female_bv173_uranus_bigtts', 'Diana', 'Brazilian Portuguese', 'Female', 'General'),
    ('pt_female_bv173emotion_uranus_bigtts', 'Lola', 'Brazilian Portuguese', 'Female', 'General'),
    ('pt_male_bv172_uranus_bigtts', 'Sam', 'Brazilian Portuguese', 'Male', 'General'),
    ('pt_female_bv173dialogue_uranus_bigtts', 'Elena', 'Brazilian Portuguese', 'Female', 'Dubbing'),
    ('pt_male_bv172emotion_uranus_bigtts', 'Vincent', 'Brazilian Portuguese', 'Male', 'Education'),
    ('ar_female_dina_uranus_bigtts', 'Dina', 'Arabic', 'Female', 'General'),
    ('ar_male_youssef_uranus_bigtts', 'Youssef', 'Arabic', 'Male', 'General'),
    ('ar_female_fatma_uranus_bigtts', 'Fatma', 'Arabic', 'Female', 'Entertainment'),
    ('de_male_sven_uranus_bigtts', 'Sven', 'German', 'Male', 'General'),
    ('de_female_bv081_uranus_bigtts', 'Stella', 'German', 'Female', 'Education'),
    ('es_male_guillem_uranus_bigtts', 'Guillem', 'Spanish', 'Male', 'AudioBook'),
    ('es_male_dani_uranus_bigtts', 'Dani', 'Spanish', 'Male', 'AudioBook'),
    ('es_female_bv084_uranus_bigtts', 'Gracie', 'Spanish', 'Female', 'General'),
    ('es_female_ht_mx_f6_uranus_bigtts', 'Marisol', 'Spanish', 'Female', 'General'),
    ('fr_female_fr_bv078_uranus_bigtts', 'Simone', 'French', 'Female', 'Dubbing'),
    ('fr_male_usseau_uranus_bigtts', 'Usseau', 'French', 'Male', 'General'),
    ('fr_female_fr_f47_uranus_bigtts', 'Camille', 'French', 'Female', 'CustomerService'),
    ('fr_male_fr_m29_uranus_bigtts', 'Maurice', 'French', 'Male', 'Dubbing'),
    ('it_male_enzo_uranus_bigtts', 'Enzo', 'Italian', 'Male', 'General'),
    ('ru_female_sophie_uranus_bigtts', 'Ksenia', 'Russian', 'Female', 'General'),
    ('ru_male_pavel_uranus_bigtts', 'Pavel', 'Russian', 'Male', 'General'),
    ('ru_female_irinae_uranus_bigtts', 'Irinae', 'Russian', 'Female', 'AudioBook'),
    ('ru_female_af07_uranus_bigtts', 'Amelia', 'Russian', 'Female', 'AudioBook'),
    ('ru_male_vlad_uranus_bigtts', 'Silas', 'Russian', 'Male', 'Entertainment'),
]

TTS_2_VOICE_IDS = [voice[0] for voice in TTS_2_VOICES]
DEFAULT_TTS_VOICE = "en_female_stokie_uranus_bigtts"
